services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - mock_accrual
    networks:
      - app_net
    volumes:
      - type: bind
        source: ../
        target: /app
    ports:
      - "8080:8080"
    environment:
      RUN_ADDRESS: localhost:8080
      DATABASE_URI: user=root password=root host=db port=5432 dbname=testdb sslmode=disable
      ACCRUAL_SYSTEM_ADDRESS: http://mock_accrual:3000
      SECRET_KEY: ohmysecretkey

  db:
    image: postgres:16.2-alpine3.19
    ports:
      - "54345:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "testdb"
    restart: always
    networks:
      - app_net
  mock_accrual:
    build:
      context: .
      dockerfile: ../test/mock_accrual/Dockerfile
    depends_on:
      - db
    networks:
      - app_net
    volumes:
      - type: bind
        source: ../
        target: /app
    expose:
      - "3000"

networks:
  app_net:
    driver: bridge
